### ISSUE TITLE
 anamorphic sharpen filter causes flickering and flashes in Alyx

### ISSUE THREAD

**Issue by conecta6** [Fubaxiusz/fubax-shaders#22] opened 2024-08-14 00:15 UTC
Currently, the anamorphic sharpen filter causes flickering and flashes in Alyx. I hadn't used it in a while, but after reinstalling it, this issue occurs. It didn't happen before.

**Comment by Fubaxiusz** [comment] 2024-08-15 04:00
The flickering may be caused by ReShade disabling depth buffer access when network activity in the game is detected. The filter uses depth buffer for this "anamorphic" effect and ReShade may block it prevent cheating in online competitive games.

So the issue is not with the shader probably, but with the anti-cheat mechanisms within ReShade.

What I can suggest is to try DisplayDepth.fx and see if it also flickers. Also you could block network access for the Alyx exe within Windows Defender Firewall and see if it helps.

**Comment by conecta6** [comment] 2024-08-16 00:22
is solved by disabling auto fidelity -console -vconsole +vr_fidelity_level_auto 0 +vr_fidelity_level 3 in the alyx launch options.

**Comment by Fubaxiusz** [comment] 2024-08-16 16:37
Ok, I'm closing this issue.

**Closed as completed by Fubaxiusz** 2024-08-16 16:37 UTC
